FROM node:22.14-slim as app-react-image
ARG VITE_ENVIRONMENT
ARG VITE_APP_VERSION
ARG VITE_SENTRY_DSN
ENV VITE_ENVIRONMENT=$VITE_ENVIRONMENT
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_SENTRY_DSN=$VITE_SENTRY_DSN
RUN npm config set registry https://registry.npmmirror.com
WORKDIR /front
ADD ./frontend /front
RUN yarn config set registry https://registry.npmmirror.com && yarn install && yarn build

FROM python:3.13.2-slim
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
RUN sed -i 's/deb.debian.org/mirrors.tencent.com/g' /etc/apt/sources.list.d/debian.sources && sed -i 's/security.debian.org/mirrors.tencent.com/g' /etc/apt/sources.list.d/debian.sources
RUN apt-get update && apt-get install -y --no-install-recommends build-essential libpq-dev supervisor nano gdal-bin && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /home/app/backend && mkdir -p /home/app/logs
RUN addgroup --system app && adduser --system --group app
WORKDIR /home/app
COPY ./backend/pyproject.toml ./backend/uv.lock ./
RUN pip install --upgrade pip -i https://mirrors.cloud.tencent.com/pypi/simple && pip install uv -i https://mirrors.cloud.tencent.com/pypi/simple && uv sync --frozen --no-dev && rm -rf uv.lock pyproject.toml
COPY ./backend ./backend
COPY --chown=app:app --from=app-react-image /front/dist /home/app/backend/frontend/dist
RUN chown -R app:app /home/app
USER app
EXPOSE 8000
CMD supervisord -c ./backend/supervisord.conf
